# Generated by Django 4.1.1 on 2022-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telecom_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mccmnc', models.CharField(max_length=6)),
                ('operator', models.TextField()),
                ('country', models.TextField()),
                ('mgt', models.CharField(max_length=15)),
                ('ngt', models.CharField(max_length=15, null=True)),
                ('prepaid_OBV', models.BooleanField()),
                ('prepaid_OBMTV', models.BooleanField(blank=True, null=True)),
                ('prepaid_OBD', models.BooleanField(blank=True, null=True)),
                ('postpaid_OBV', models.BooleanField(blank=True, null=True)),
                ('postpaid_OBD', models.BooleanField(blank=True, null=True)),
                ('one_network', models.BooleanField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('tapcode', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
